name: Label PRs
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  check-paths:
      uses: ./.github/workflows/check-diff.yaml
  label_pr:
    needs: check-paths
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.pull_request.number }}
    permissions:
      pull-requests: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "backend"
        if: ${{ needs.check-paths.outputs.backend == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "backend"
        if: ${{ needs.check-paths.outputs.backend == 'false' }}
      
      - run: gh issue edit "$NUMBER" --add-label "graphql-schema"
        if: ${{ needs.check-paths.outputs.graphql-schema == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "graphql-schema"
        if: ${{ needs.check-paths.outputs.graphql-schema == 'false' }}
      
      - run: gh issue edit "$NUMBER" --add-label "ios"
        if: ${{ needs.check-paths.outputs.ios == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "ios"
        if: ${{ needs.check-paths.outputs.ios == 'false' }}

      - run: gh issue edit "$NUMBER" --add-label "web"
        if: ${{ needs.check-paths.outputs.web == 'true' }}
      - run: gh issue edit "$NUMBER" --remove-label "web"
        if: ${{ needs.check-paths.outputs.web == 'false' }}
