name: PR

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/graphql/schema.graphql'
      - 'ios/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  ios-test:
    uses: ./.github/workflows/ios-build.yaml
    with:
      deploy: false
      skip: false
